ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.confusing-naming]
[rule.confusing-results]
[rule.defer]
[rule.datarace]
[rule.deep-exit]
[rule.early-return]
[rule.enforce-map-style]
[rule.enforce-slice-style]
[rule.identical-branches]
[rule.if-return]
[rule.unnecessary-stmt]
[rule.unconditional-recursion]
[rule.unchecked-type-assertion]
[rule.optimize-operands-order]
[rule.import-shadowing]
[rule.import-alias-naming]
[rule.atomic]

[rule.package-comments]
  Disabled = true
